name: Vacancies Checker

on:
  schedule:
    - cron: '0 3,6,9,12,15 * * *'
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y wget curl unzip
        curl -sSL https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb -o google-chrome.deb
        sudo dpkg -i google-chrome.deb
        sudo apt --fix-broken install
        # CHROME_DRIVER_VERSION=$(google-chrome-stable --version | sed 's/[^0-9.]//g')
        # wget https://chromedriver.storage.googleapis.com/${CHROME_DRIVER_VERSION}/chromedriver_linux64.zip
        wget https://github.com/jsnjack/chromedriver/releases/download/v143.0.7499.192/chromedriver-linux64.zip
        unzip chromedriver-linux64.zip
        sudo mv chromedriver /usr/local/bin/chromedriver
        sudo chmod +x /usr/local/bin/chromedriver
        pip install -r requirements.txt

    - name: Run script
      env:
        LLM_API_KEY: ${{ secrets.LLM_API_KEY }}
        TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
      run: |
        python main.py

    - name: Commit and push index.html
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add vacancies.o
        git commit -m "upd: vacancies.json" || exit 0
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}